### ISSUE TITLE
possible optimization opportunity (saves ~13% execution time)

### ISSUE THREAD

**Issue by emeryberger** [vivaladav/pyfinder#1]
https://twitter.com/emeryberger/status/1256066475288379392

I profiled it with [Scalene](https://github.com/emeryberger/scalene) and quickly found a modest improvement. The bounds check in `astar.py:handle_node` never gets executed in any tests (presumably guarded by its caller); commenting out improves perf by ~13%.

**Comment by vivaladav** [comment]
Hi @emeryberger and thanks for checking my code with Scalene.

That if is never true because all the current maps have a non-walkable border, but it's logically correct and needed.

I can't remove it completely, but I will move the checks outside to reduce the number of ifs.

**Comment by vivaladav** [comment]
Moving those checks out of handle_node didn't give any real performance boost, but made the code less readable.

Sorry, but I am not going to commit this change.
